name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v1
    - name: Install GRASS GIS and other dependencies
      run: |
        apt-get update -qq
        apt-get install -y -qq grass grass-dev grass-doc wget
    - name: Fix GRASS GIS installation for g.extension
      run: |
        wget https://grass.osgeo.org/grass74/manuals/grass_logo.png
        wget https://grass.osgeo.org/grass74/manuals/grassdocs.css
        mv grass_logo.png /usr/lib/grass74/docs/html/grass_logo.png
        mv grassdocs.css /usr/lib/grass74/docs/html/grassdocs.css
    - name: Create a temporary location (needed for 7.4 and below)
      run: |
        grass -c EPSG:4326 ~/grasstmploc -e
    - name: Chanage shebang to just Python (7.4 needs python2)
      run: |
        sed -i s/python3/python/g r.example.plus.py
        sed -i s/python3/python/g testsuite/test_r_example_plus.py
    - name: Install the module
      run: |
        grass ~/grasstmploc/PERMANENT --exec g.extension extension=${{ github.repository }} url=. --verbose
    - name: Get sample data for testing
      run: |
        grass ~/grasstmploc/PERMANENT --exec g.extension g.download.location --verbose
        grass ~/grasstmploc/PERMANENT --exec g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_08_grass7.tar.gz --verbose
    - name: Run test
      run: |
        cd testsuite/
        grass -c ~/nc_spm_08_grass7/test --exec ./test_r_example_plus.py
        rm -rf ~/nc_spm_08_grass7/test
